name: base
channels:
- pytorch
- bokeh
- plotly
- conda-forge
- anaconda
dependencies:
- nodejs
# JupyterLab
- jupyterlab
- jupyterhub
- ipywidgets
- jupyter-server-proxy
- jupyterlab-git
- jupyterlab-lsp
- jupyterlab_latex
- jupyterlab-katex
- jupyterlab-mathjax3
- jupyterlab-language-pack-ru-RU
- jupyterlab-system-monitor
- jupyterlab-unfold
- jupyter-archive
- jupyterlab-spellchecker
- mamba_gator
- jupyterlab-fonts
- jupyterlab-drawio
- jupyterlab-favorites
- jupyterlab-recents
- jupyterlab-notifications
- jupyter_bokeh
- jupyterlab-tour
- jupyterlab-fileopen
- jupyterlab_code_formatter
- jupyterlab_execute_time
- jupyterlab-nvdashboard
# Plotting, visualization
- matplotlib
- ipympl
- seaborn
- plotly
- bokeh
- mayavi
- cycler
- plotly
- ipygany
- voila
# ML
#- cudatoolkit=11.3
#- pytorch
#- torchvision
#- tensorflow-gpu
#- tensorboard
#- pytorch-lightning
#- tensorboardx
#- scikit-learn
#- scipy
#- pydot
#- catboost
#- statsmodels
#- jax
# Image processing
#- opencv
#- pillow
#- cython
#- scikit-image
#- pywavelets
# unit-testing
#- nose
#- pytest
#- pytest-cov
#- pytest-faulthandler
# other
- conda-build
- pip
- mne
- decorator
- jinja2
- numpy
- pandas
- pyqt
- python-dateutil
- requests
- sympy
- tqdm
- dill
- protobuf
- ldap3
- ptvsd
- python-lsp-server
- black
- python-lmdb
- texlab
- chktex
- pip:
  - pyro-ppl 
  - jupyter-tensorboard
  - arxiv
  - python-picard
  - bash_kernel
  - thop
  - jupyterlab-quickopen
  - jupyterlab-horizon-theme
  - jupyterlab-shanshu-theme
  - jupyterlab_theme_sophon
  - epi2melabs_theme
  - jupyterlab-prodigy
  - jupyterlab-spreadsheet-editor
  - jupyterlab_markup
  - databeanstalk-theme
  - jupyterlab_theme_hale
  - jupyterlab_hdf
#jupyterhub
  - jupyterhub-systemdspawner
  - jupyterhub-ldap-authenticator


